name: Sort Imports with isort

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  # pull_request:
  #   branches: [ master ]
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "format"
  format:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Job-level permissions configuration starts here
    permissions:
      contents: write           # 'write' access to repository contents

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v5

    - name: Run isort
      uses: olance/isort-action@79c441b9e46c88ab6cfcdaf83043569b70bbc17d
      with:
        args: .

    - name: Commit changes
      run: |
        git config --local user.email "actions@github.com"
        git config --local user.name "GitHub Actions"
        git add -A && git diff-index --cached --quiet HEAD || git commit -m 'isort auto-applied'

    - name: Push changes
      uses: ad-m/github-push-action@v1.0.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: master
